### ISSUE TITLE
关于使用代理的问题

### ISSUE THREAD

**Issue by jimmyhu517** [formateddd/pornhub#18]
我用shadowsocks科学上万，用pac模式的时候，无法链接到pornhub，只有在全局模式下，才能访问到。那么能有什么方式让这个工具自动走ss，或者让他的流量通过ss的代理呢

**Comment by formateddd** [comment]
最简单的办法，把PH的域名加到你的代理名单里。

**Comment by xgj1988** [comment]
@jimmyhu517  你搞定没。。pornhub.com域名添加到代理名单里面了也没用啊。

**Comment by formateddd** [comment]
真正下载视频的链接是ph的子域名，phncdn.com，把这个加进去

**Comment by formateddd** [comment]
那就直接去可以翻墙的服务器运行吧，下载完用scp命令或者winscp之类的软件从服务器下载下来

**Comment by xgj1988** [comment]
@formateddd 加了个代码，这样请求的时候指定一下代理就可以了。
proxies = {'http': 'http://localhost:1080', 'https': 'http://localhost:1080'}
 resp = requests.get(url, proxies=proxies, headers=headers)

**Comment by jimmyhu517** [comment]
@xgj1988 老哥牛逼

**Comment by jimmyhu517** [comment]
@xgj1988 老哥牛逼。
@formateddd 大神也牛逼

**Comment by formateddd** [comment]
如果没有个人的代理服务器，网上找到的一般不很稳定，所以不推荐。大家新年快乐
