### ISSUE TITLE
Could not install packages due to an EnvironmentError: [Errno 13]

### ISSUE THREAD

**Issue by murongqiaochu** [formateddd/pornhub#19]
manlindeMacBook-Pro:pornhub manlin$ cd Pornhub && pip install -r requirements.txt
Collecting requests (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting lxml (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/80/c7/909a16707823c169770e024e1495bc691b067bb45c032bb81039ad455d02/lxml-4.3.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting fire (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/5a/b7/205702f348aab198baecd1d8344a90748cb68f53bdcd1cc30cbc08e47d3e/fire-0.1.3.tar.gz
Collecting loguru (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/8f/ec/37bd2bf520fd227d0b1bb206298ed903ede9a1d6e83dfc76df2a6a7a044c/loguru-0.0.1.tar.gz
Collecting urllib3<1.25,>=1.21.1 (from requests->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from fire->-r requirements.txt (line 3)) (1.4.1)
Installing collected packages: urllib3, certifi, chardet, idna, requests, lxml, fire, loguru
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/urllib3-1.24.1.dist-info'
Consider using the `--user` option or check the permissions.

**Comment by formateddd** [comment]
权限问题，pip前加sudo执行

**Comment by formateddd** [comment]
确定是root？那你试一下virtualenv建个虚拟环境，要py3的

**Comment by murongqiaochu** [comment]
> 确定是根？那你试一下的virtualenv建个虚拟环境，要PY3的

我之前尝试了下其他的源码，安装了一些乱七八糟的东西😂现在好用了，麻烦您了。谢谢
