### ISSUE TITLE
 __init__() got an unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by llh1187** [formateddd/pornhub#23]
im a green hand.
somebody can help me ?
//
我是菜鸟
有人可以帮俺一下吗

**Comment by formateddd** [comment]
按你的错误信息搜到的
https://stackoverflow.com/questions/38155320/firebase-get-request-typeerror-init-got-an-unexpected-keyword-argument

**Comment by llh1187** [comment]
谢谢你~
