### ISSUE TITLE
貌似下载失效了，能读出名称，却没下载下来

### ISSUE THREAD

**Issue by Ro0kie** [formateddd/pornhub#27]
(pornhub) E:\******\Pornhub>python crawler.py mp4
2019-10-27 01:50:18.329 | INFO     | __main__:run:101 - url: https://www.pornhub.com/view_video.php?viewkey=ph5a8a329048ecb
2019-10-27 01:50:22.144 | INFO     | __main__:detail_page:50 - jade laroche
2019-10-27 01:50:22.152 | INFO     | __main__:run:110 - finish !

名称是对的，但是1秒不到就显示finish 了

**Comment by Ro0kie** [comment]
'mediaDefinitions': [   {   'defaultQuality': False,
                                'format': 'mp4',
                                'quality': '720',
                                'videoUrl': ''},
                            {   'defaultQuality': False,
                                'format': 'hls',
                                'quality': '720',
                                'videoUrl': ''},
                            {   'defaultQuality': False,
                                'format': 'mp4',
                                'quality': '480',
                                'videoUrl': ''},
                            {   'defaultQuality': True,
                                'format': 'hls',
                                'quality': '480',
                                'videoUrl': ''},
                            {   'defaultQuality': False,
                                'format': 'mp4',
                                'quality': '240',
                                'videoUrl': ''},
                            {   'defaultQuality': False,
                                'format': 'hls',
                                'quality': '240',
                                'videoUrl': ''},
                            {   'defaultQuality': True,
                                'format': 'hls',
                                'quality': [720, 480, 240],
                                'videoUrl': ''}],


我发现是 videourl都是空的。。。
奇了怪了

**Comment by LotusQing** [comment]
会改吗？

**Comment by Ro0kie** [comment]
> 会改吗？

我看了下，。这个项目的方法应该是失效了， json已经不显示videourl了，  建议你直接用youtbe-dl 下载

**Comment by yeluoge26** [comment]
会改吗？

**Comment by yeluoge26** [comment]
> > 会改吗？
> 
> 我看了下，。这个项目的方法应该是失效了， json已经不显示videourl了， 建议你直接用youtbe-dl 下载

youtube-dl也无法批量下载了，都失效了。目前所有的基于youtube-dl得全部都是显示encode error了

**Comment by Ro0kie** [comment]
> > > 会改吗？
> > 
> > 
> > 我看了下，。这个项目的方法应该是失效了， json已经不显示videourl了， 建议你直接用youtbe-dl 下载
> 
> youtube-dl也无法批量下载了，都失效了。目前所有的基于youtube-dl得全部都是显示encode error了

我记得youtube-dl 单个下载还是没问题的吧。。

**Comment by yeluoge26** [comment]
> > > > 会改吗？
> > > 
> > > 
> > > 我看了下，。这个项目的方法应该是失效了， json已经不显示videourl了， 建议你直接用youtbe-dl 下载
> > 
> > 
> > youtube-dl也无法批量下载了，都失效了。目前所有的基于youtube-dl得全部都是显示encode error了
> 
> 我记得youtube-dl 单个下载还是没问题的吧。。

是的，所有计划是重写调用youtube-dl逐个下载，只能这样先了。

**Comment by leetomlee123** [comment]
selenium

**Comment by leetomlee123** [comment]
chrome_options = webdriver.Options()
    # 使用headless无界面浏览器模式
    chrome_options.add_argument('--headless')
    chrome_options.add_argument('--disable-gpu')
    # 启动浏览器，获取网页源代码
    browser = webdriver.WebDriver(options=chrome_options)

    browser.get(url)
    html = etree.HTML(browser.page_source)
    videoUrl = html.xpath('//source[@type="video/mp4"]/@src')[0]``

**Comment by Itachi6688** [comment]
> ```
> chrome_options = webdriver.Options()
> # 使用headless无界面浏览器模式
> chrome_options.add_argument('--headless')
> chrome_options.add_argument('--disable-gpu')
> # 启动浏览器，获取网页源代码
> browser = webdriver.WebDriver(options=chrome_options)
> 
> browser.get(url)
> html = etree.HTML(browser.page_source)
> videoUrl = html.xpath('//source[@type="video/mp4"]/@src')[0]``
> ```

老哥，怎么玩呀 不是很懂 哈哈

**Comment by formateddd** [comment]
更新了 再试试看

**Comment by yeluoge26** [comment]
我自己也改了下，但是下载速度只有100多k，不知道为啥，

**Comment by yeluoge26** [comment]
怎么上传分支啊，我在原来的基础上改了下
> 更新了 再试试看

**Comment by hnzyc** [comment]
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.pornhub.com', port=443): Max retries exceeded with url: /video?o=tr (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')")))
出现sslError该怎么解决啊？谢谢

**Comment by formateddd** [comment]
> 怎么上传分支啊，我在原来的基础上改了下
> 
> > 更新了 再试试看

fork一下 再上传
