### ISSUE TITLE
好像无法获取到qualit_720p等的视频链接了？

### ISSUE THREAD

**Issue by pyh99715** [formateddd/pornhub#32]
你好，我使用您代码的过程中，首先报错是找不到视频链接，我挨个看了下变量，发现在下载mp4的时候在执行crawler.py文件中detail_page函数中videoUrl = exeJs(js)这一句的返回值为None，看了下对应函数发现对flashvars_xxxxxxxx变量的获取返回中没有视频的链接，我登陆网站console.log(flashvars_xxxxx)是可以获取到这个值的，我尝试自己修改但是好像没有成功，您看看会不会是出什么问题了呢

**Comment by ald2004** [comment]
videoUrl 改了,需要更新了...

**Comment by formateddd** [comment]
@pyh99715 @ald2004 更新了方法 再试试看
