### ISSUE TITLE
SOCKSHTTPSConnectionPool(host='cn.pornhub.com', port=443): Max retries exceeded with url: /playlist/100503721 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000141C8A83908>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

### ISSUE THREAD

**Issue by android0221** [formateddd/pornhub#33]
SOCKSHTTPSConnectionPool(host='cn.pornhub.com', port=443): Max retries exceeded with url: /playlist/100503721 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000141C8A83908>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by formateddd** [comment]
尝试把sock5换到http方式，注意修改端口
