### ISSUE TITLE
好像有点问题

### ISSUE THREAD

**Issue by 20has** [formateddd/pornhub#34]
安装环境 
[root@lxc-centos7 Pornhub]# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)

安装步骤：
yum -y install git python3 python3-pip
git clone https://github.com/killmymates/Pornhub
cd Pornhub && pip3 install -r requirements.txt 
python3 crawler.py webm

#报错情况：
[root@lxc-centos7 Pornhub]# python3 crawler.py webm
2020-07-06 06:17:27.713 | INFO     | __main__:list_page:34 - crawling : https://cn.pornhub.com/playlist/100503721
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cn.pornhub.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
2020-07-06 06:17:29.720 | INFO     | __main__:run:153 - finish !

[root@lxc-centos7 Pornhub]# cat logs/crawler.log
07-06 06:17:27 INFO crawling : https://cn.pornhub.com/playlist/100503721
07-06 06:17:29 INFO finish !

[root@lxc-centos7 Pornhub]# tree
.
|-- README.md
|-- _config.yml
|-- crawler.py
|-- download.txt
|-- logs
|   -- crawler.log
|-- mp4
|-- png
|   -- zhifubao.png
|-- requirements.txt
|-- tampermonkey.js
-- webm
4 directories, 8 files

[root@lxc-centos7 Pornhub]# ll webm/
total 0

好像webm目录下没有任何东西

**Comment by formateddd** [comment]
更新了 再试试看

**Comment by 20has** [comment]
[root@localhost Pornhub]# python3 crawler.py webm
2020-07-11 09:44:46.934 | INFO     | __main__:list_page:33 - crawling : https://www.pornhub.com/video
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.pornhub.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.4shared.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Traceback (most recent call last):
  File "crawler.py", line 155, in <module>
    fire.Fire(run)
  File "/usr/local/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "crawler.py", line 127, in run
    list_page(url)
  File "crawler.py", line 38, in list_page
    names = html.xpath(f"{buff}@href")
AttributeError: 'NoneType' object has no attribute 'xpath'

#换了个虚拟机运行 好像还是这个 错误
#改了配置文件，自己lede的socket5代理

**Comment by 20has** [comment]
好像还是代理的问题？  我在美国硅谷的vps执行居然成功了 。。。
