### ISSUE TITLE
AttributeError: 'str' object has no attribute 'quality_720p'

### ISSUE THREAD

**Issue by Live4dreamCH** [formateddd/pornhub#36]
File "crawler.py", line 76, in exeJs
    if res.quality_720p:
AttributeError: 'str' object has no attribute 'quality_720p'

**Comment by zzzop** [comment]
请问怎么解决的，一样的报错

**Comment by YuhooZhu** [comment]
> 请问怎么解决的，一样的报错
有个js方法里有个正则匹配, debug一下那个js好了, 官方有时好像会改结构
